### ISSUE TITLE
Cant fetch stored parameters more than 10

### ISSUE THREAD

**Issue by fl-errol-fernandes** [albertomr86/nestjs-param-store#4]
The library does not retrieve more than 10 stored parameters

**Comment by albertomr86** [comment]
Thank you for reporting the issue. This is a bug in the library.

The `GetParametersByPath` command has pagination by default with a max limit of 10 results according to the [doc](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_GetParametersByPath.html#API_GetParametersByPath_RequestSyntax).

**Comment by errolflexiloan** [comment]
@albertomr86 any timelines if this can be fixed.?

**Comment by albertomr86** [comment]
Fixed starting at version `1.2.0`
