### ISSUE TITLE
chore: add support for NestJS 10

### ISSUE THREAD

**Issue by albertomr86** [albertomr86/nestjs-param-store#7]

**Comment by matangist** [comment]
+1

**Comment by fauxbytes** [comment]
Hi. Would love to see this fixed. FWIW, tried [this](https://github.com/albertomr86/nestjs-param-store/pull/14)? `npm run test` passes, plus I installed a local package in a nest10 app, and it seems to work fine. Many thanks.

**Comment by albertomr86** [comment]
Merged.  The version `v1.3.1` is now available with support for NestJS 10. Thanks.
